import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { telegramCommandCatalog, type ControllerSetup, type OpenClawSetupMode, type SecretRef } from "../../core/src/index.js";

const envBlockStart = "# AUTO FORGE VPS SETUP START";
const envBlockEnd = "# AUTO FORGE VPS SETUP END";

export interface NginxConfigInput {
  serverName: string;
  apiPort?: number;
  webPort?: number;
  apiHost?: string;
  webHost?: string;
}

export interface SecretInput {
  envName: string;
  value?: string;
  ref?: SecretRef;
}

export interface VpsSetupRecordInput {
  openClawBaseUrl: string;
  openClawMode?: OpenClawSetupMode;
  openClawAuthRef?: SecretRef;
  openClawToken?: SecretInput;
  openClawAgentHookPath?: string;
  openClawDiscovery?: ControllerSetup["openClaw"]["discovery"];
  telegramBotToken: SecretInput;
  telegramTestChatId: string;
  configuredByUserId?: string;
  registerTelegramCommands?: boolean;
  sendTestMessage?: boolean;
  now?: Date;
}

export interface EnvWriteResult {
  path: string;
  updatedKeys: string[];
}

export interface TelegramChatCandidate {
  chatId: string;
  userId?: string;
  type?: string;
  title?: string;
  username?: string;
  firstName?: string;
  lastName?: string;
}

export type TelegramChatDiscoveryFallback = "retry" | "manual";

export interface SelectTelegramChatIdOptions {
  initialAnswer: string;
  discoverChats: () => Promise<TelegramChatCandidate[]>;
  promptDiscoveredChat: (candidates: TelegramChatCandidate[]) => Promise<string>;
  promptManualChatId: () => Promise<string>;
  promptDiscoveryFallback: (context: {
    reason: "empty" | "error";
    message: string;
    error?: Error;
  }) => Promise<TelegramChatDiscoveryFallback>;
  onMessage?: (message: string) => void;
}

interface TelegramUpdatesResponse {
  ok: boolean;
  result?: Array<{
    message?: {
      chat?: TelegramChatCandidate & { id: number | string; first_name?: string; last_name?: string };
      from?: { id?: number | string };
    };
    channel_post?: {
      chat?: TelegramChatCandidate & { id: number | string; first_name?: string; last_name?: string };
    };
    my_chat_member?: {
      chat?: TelegramChatCandidate & { id: number | string; first_name?: string; last_name?: string };
      from?: { id?: number | string };
    };
  }>;
  description?: string;
}

export function generateNginxConfig(input: NginxConfigInput): string {
  const serverName = input.serverName.trim();
  if (!serverName) {
    throw new Error("Nginx serverName is required");
  }

  const apiHost = input.apiHost ?? "127.0.0.1";
  const webHost = input.webHost ?? "127.0.0.1";
  const apiPort = input.apiPort ?? 3000;
  const webPort = input.webPort ?? 5173;

  return `# Auto Forge Controller Nginx site
# Generated by npm run setup:vps. Review before enabling in production.
# TLS note: install Certbot or use an existing VPS TLS manager before Telegram webhook production use.

upstream auto_forge_api {
    server ${apiHost}:${apiPort};
}

upstream auto_forge_web {
    server ${webHost}:${webPort};
}

server {
    listen 80;
    server_name ${serverName};

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location = /health {
        proxy_pass http://auto_forge_api;
    }

    location = /live {
        proxy_pass http://auto_forge_api;
    }

    location ^~ /setup {
        proxy_pass http://auto_forge_api;
    }

    location = /telegram/command {
        proxy_pass http://auto_forge_api;
    }

    location = /telegram/webhook {
        proxy_pass http://auto_forge_api;
    }

    location ^~ /approvals/ {
        proxy_pass http://auto_forge_api;
    }

    location ^~ /workflow/ {
        proxy_pass http://auto_forge_api;
    }

    location ^~ /tasks {
        proxy_pass http://auto_forge_api;
    }

    location / {
        proxy_pass http://auto_forge_web;
    }
}
`;
}

export function buildControllerSetup(input: VpsSetupRecordInput): ControllerSetup {
  const baseUrl = new URL(input.openClawBaseUrl);
  baseUrl.pathname = baseUrl.pathname.replace(/\/+$/, "");

  return {
    configuredByUserId: input.configuredByUserId ?? "vps-setup-wizard",
    updatedAt: (input.now ?? new Date()).toISOString(),
    openClaw: {
      baseUrl: baseUrl.toString().replace(/\/$/, ""),
      mode: input.openClawMode ?? (input.openClawAuthRef ? "advanced-webhook" : "detect-existing"),
      authRef: input.openClawAuthRef ?? (input.openClawToken ? resolveSecretRef(input.openClawToken) : undefined),
      tokenRef: input.openClawToken ? resolveSecretRef(input.openClawToken) : undefined,
      agentHookPath: input.openClawAgentHookPath ?? "/hooks/agent",
      discovery: input.openClawDiscovery
    },
    telegram: {
      botTokenRef: resolveSecretRef(input.telegramBotToken),
      testChatId: input.telegramTestChatId,
      registerCommands: input.registerTelegramCommands ?? true,
      sendTestMessage: input.sendTestMessage ?? true,
      commands: telegramCommandCatalog.map((command) => command.command)
    }
  };
}

export function buildVpsEnvValues(input: {
  publicBaseUrl: string;
  apiPort: number;
  webPort: number;
  openClawBaseUrl: string;
  openClawMode?: OpenClawSetupMode;
  openClawAuthRef?: SecretRef;
  openClawToken?: SecretInput;
  telegramBotToken: SecretInput;
  telegramTestChatId: string;
  telegramOperatorChatId?: string;
  telegramOperatorUserId?: string;
  codexAuthRef: SecretRef;
  codexApiKey?: SecretInput;
  telegramWebhookSecret?: string;
  databaseUrl?: string;
  hostDataDir?: string;
  codexAuthSourceDir?: string;
  setupPath?: string;
  runtimeSetupPath?: string;
}): Record<string, string> {
  const artifactRoot = input.hostDataDir ? `${input.hostDataDir}/artifacts` : "/data/artifacts";
  const promptRoot = input.hostDataDir ? `${input.hostDataDir}/prompts` : "/data/prompts";
  const codexHome = input.hostDataDir ? `${input.hostDataDir}/codex-home` : "/data/codex-home";
  const values: Record<string, string> = {
    AUTO_FORGE_PUBLIC_BASE_URL: input.publicBaseUrl,
    AUTO_FORGE_RUNTIME_CONTEXT: "host",
    AUTO_FORGE_API_HEALTH_URL: new URL("/live", input.publicBaseUrl).toString(),
    AUTO_FORGE_WEB_HEALTH_URL: `http://127.0.0.1:${input.webPort}/`,
    AUTO_FORGE_DATA_DIR: "/data",
    AUTO_FORGE_LOG_DIR: "/data/logs",
    AUTO_FORGE_BACKUP_DIR: "/data/backups",
    AUTO_FORGE_WORKER_HEALTH_PATH: "/data/worker-health.json",
    AUTO_FORGE_ARTIFACT_ROOT: artifactRoot,
    AUTO_FORGE_PROMPT_ROOT: promptRoot,
    AUTO_FORGE_CODEX_AUTH_SOURCE_DIR: input.codexAuthSourceDir ?? "/codex-auth-source",
    CODEX_HOME: codexHome,
    DATABASE_URL: input.databaseUrl ?? "postgres://auto_forge:auto_forge@postgres:5432/auto_forge",
    VITE_API_BASE_URL: input.publicBaseUrl,
    PORT: String(input.apiPort),
    OPENCLAW_BASE_URL: input.openClawBaseUrl,
    OPENCLAW_SETUP_MODE: input.openClawMode ?? (input.openClawAuthRef ? "advanced-webhook" : "detect-existing"),
    TELEGRAM_BOT_TOKEN_REF: resolveSecretRef(input.telegramBotToken),
    TELEGRAM_TEST_CHAT_ID: input.telegramTestChatId,
    CODEX_AUTH_REF: input.codexAuthRef,
    AUTO_FORGE_SETUP_PATH: input.runtimeSetupPath ?? input.setupPath ?? ".auto-forge/setup.json"
  };
  if (input.hostDataDir) {
    values.AUTO_FORGE_HOST_DATA_DIR = input.hostDataDir;
  }
  if (input.telegramOperatorChatId) {
    values.TELEGRAM_OPERATOR_CHAT_ID = input.telegramOperatorChatId;
  }
  if (input.telegramOperatorUserId) {
    values.TELEGRAM_OPERATOR_USER_ID = input.telegramOperatorUserId;
  }

  const openClawAuthRef = input.openClawAuthRef ?? (input.openClawToken ? resolveSecretRef(input.openClawToken) : undefined);
  if (openClawAuthRef) {
    values.OPENCLAW_AUTH_REF = openClawAuthRef;
    values.OPENCLAW_TOKEN_REF = openClawAuthRef;
  }

  if (input.telegramWebhookSecret) {
    values.TELEGRAM_WEBHOOK_SECRET = input.telegramWebhookSecret;
  }

  for (const secret of [input.openClawToken, input.telegramBotToken, input.codexApiKey].filter(Boolean) as SecretInput[]) {
    if (secret.value) {
      values[secret.envName] = secret.value;
    }
  }

  return values;
}

export async function writeEnvBlock(path: string, values: Record<string, string>): Promise<EnvWriteResult> {
  await mkdir(dirname(path), { recursive: true });
  const existing = await readTextIfPresent(path);
  const nextBlock = [
    envBlockStart,
    "# Written by npm run setup:vps. Keep this file out of Git and mode 0600.",
    ...Object.entries(values)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, value]) => `${key}=${formatEnvValue(value)}`),
    envBlockEnd
  ].join("\n");

  const next = existing.includes(envBlockStart) && existing.includes(envBlockEnd)
    ? existing.replace(new RegExp(`${escapeRegExp(envBlockStart)}[\\s\\S]*?${escapeRegExp(envBlockEnd)}`), nextBlock)
    : `${existing.trimEnd()}${existing.trim() ? "\n\n" : ""}${nextBlock}\n`;

  const tempPath = `${path}.tmp`;
  await writeFile(tempPath, next.endsWith("\n") ? next : `${next}\n`, { mode: 0o600 });
  await rename(tempPath, path);
  await chmod(path, 0o600);
  return { path, updatedKeys: Object.keys(values).sort() };
}

export async function discoverTelegramChatIds(options: {
  botToken: string;
  apiBaseUrl?: string;
  fetchImpl?: typeof fetch;
}): Promise<TelegramChatCandidate[]> {
  const fetchImpl = options.fetchImpl ?? fetch;
  const apiBaseUrl = options.apiBaseUrl ?? "https://api.telegram.org";
  const response = await fetchImpl(`${apiBaseUrl}/bot${options.botToken}/getUpdates`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ allowed_updates: ["message", "channel_post", "my_chat_member"] }),
    signal: AbortSignal.timeout(10_000)
  });
  const payload = (await response.json().catch(() => undefined)) as TelegramUpdatesResponse | undefined;
  if (!response.ok || !payload?.ok) {
    throw new Error(payload?.description ?? `Telegram getUpdates failed with HTTP ${response.status}`);
  }

  const unique = new Map<string, TelegramChatCandidate>();
  for (const update of payload.result ?? []) {
    const chat = update.message?.chat ?? update.channel_post?.chat ?? update.my_chat_member?.chat;
    if (chat?.id === undefined) {
      continue;
    }
    const chatId = String(chat.id);
    const userId = update.message?.from?.id ?? update.my_chat_member?.from?.id;
    const previous = unique.get(chatId);
    unique.set(chatId, stripUndefined({
      chatId,
      userId: userId === undefined ? previous?.userId : String(userId),
      type: chat.type ?? previous?.type,
      title: chat.title ?? previous?.title,
      username: chat.username ?? previous?.username,
      firstName: chat.firstName ?? chat.first_name ?? previous?.firstName,
      lastName: chat.lastName ?? chat.last_name ?? previous?.lastName
    }));
  }
  return [...unique.values()];
}

function stripUndefined<T extends Record<string, unknown>>(value: T): T {
  return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined)) as T;
}

export async function selectTelegramChatId(options: SelectTelegramChatIdOptions): Promise<string> {
  let answer = normalizeTelegramChatId(options.initialAnswer);
  while (answer === "discover") {
    try {
      const candidates = await options.discoverChats();
      if (candidates.length > 0) {
        return normalizeTelegramChatId(await options.promptDiscoveredChat(candidates));
      }

      const message = "Telegram did not return any chats yet. Send a message to the bot, then retry discovery or enter the chat ID manually.";
      options.onMessage?.(message);
      const fallback = await options.promptDiscoveryFallback({ reason: "empty", message });
      answer = fallback === "retry" ? "discover" : normalizeTelegramChatId(await options.promptManualChatId());
    } catch (error) {
      const normalizedError = error instanceof Error ? error : new Error("Telegram chat discovery failed");
      const message = `Telegram chat discovery failed: ${normalizedError.message}`;
      options.onMessage?.(message);
      const fallback = await options.promptDiscoveryFallback({
        reason: "error",
        message,
        error: normalizedError
      });
      answer = fallback === "retry" ? "discover" : normalizeTelegramChatId(await options.promptManualChatId());
    }
  }

  return answer;
}

export function resolveSecretRef(secret: SecretInput): SecretRef {
  if (secret.ref) {
    return secret.ref;
  }
  return `env:${secret.envName}`;
}

export function parseEnvFile(text: string): Record<string, string> {
  const values: Record<string, string> = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const index = trimmed.indexOf("=");
    if (index === -1) {
      continue;
    }
    const key = trimmed.slice(0, index).trim();
    const rawValue = trimmed.slice(index + 1).trim();
    values[key] = parseEnvValue(rawValue);
  }
  return values;
}

async function readTextIfPresent(path: string): Promise<string> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return "";
    }
    throw error;
  }
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
}

function parseEnvValue(value: string): string {
  if (value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replace(/\\"/g, '"').replace(/\\\$/g, "$").replace(/\\\\/g, "\\");
  }
  return value;
}

function normalizeTelegramChatId(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) {
    throw new Error("Telegram chat ID is required");
  }
  return trimmed;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
